#:kivy 2.1.0
<Header_DropDown>:
    Button:
        id: profile
        text: 'Profile'
        size_hint_y: None
        height: 44
        on_release: root.select('item1')
        on_press: root.manager.current = 'profile'
    Button:
        text: 'Profile'
        size_hint_y: None
        height: 44
        on_release: root.select('item2')
    Button:
        text: 'Profile'
        size_hint_y: None
        height: 44
        on_release: root.select('item3')