# Generated by Django 4.1.7 on 2023-06-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Zone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_patch',
        ),
    ]
