# Generated by Django 4.1.7 on 2023-06-03 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edit_course_zone.utils.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок главы')),
                ('order', edit_course_zone.utils.fields.OrderField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Главу',
                'verbose_name_plural': 'Главы',
                'ordering': ['course_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('py', 'python'), ('go', 'golang'), ('rs', 'rust'), ('kt', 'kotlin'), ('java', 'java'), ('c', 'c'), ('cs', 'cs'), ('cpp', 'cpp')], max_length=4)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Пример кода в уроке',
                'verbose_name_plural': 'Примеры кода в уроках',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('header_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Шапка курса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('visibility', models.CharField(choices=[('PR', 'Никому'), ('FC', 'Только моим классам'), ('PB', 'Всем')], default='PR', max_length=2, verbose_name='Кому виден курс')),
                ('owners', models.ManyToManyField(related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Владельцы')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name': 'Файл к уроку',
                'verbose_name_plural': 'Файлы к урокам',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Картинку к уроку',
                'verbose_name_plural': 'Картинки к урокам',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема урока')),
                ('slug', models.SlugField()),
                ('order', edit_course_zone.utils.fields.OrderField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменён в')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название таблицы')),
            ],
            options={
                'verbose_name': 'Табличную информацию в уроке',
                'verbose_name_plural': 'Табличные информации в уроках',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Тест на уроке',
                'verbose_name_plural': 'Тесты на уроках',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Текстовую часть урока',
                'verbose_name_plural': 'Текстовые части уроков',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL ссылка на видео с онлайн-сервисов')),
            ],
            options={
                'verbose_name': 'Видеоматериал к уроку',
                'verbose_name_plural': 'Видеоматериалы к урокам',
            },
        ),
        migrations.CreateModel(
            name='WriteAProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Практическую часть урока - написание программы',
                'verbose_name_plural': 'Практические части уроков - написание программ',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('order', edit_course_zone.utils.fields.OrderField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit_course_zone.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос из теста',
                'verbose_name_plural': 'Вопросы из тестов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ')),
                ('order', edit_course_zone.utils.fields.OrderField()),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit_course_zone.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Ответ в тесте',
                'verbose_name_plural': 'Ответы в тестах',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', edit_course_zone.utils.fields.OrderField(blank=True)),
                ('style', models.TextField(verbose_name='Стили, применимые к контенту ячейки')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'image')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit_course_zone.table', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Содержимое таблицы',
                'verbose_name_plural': 'Содержимое таблиц',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subchapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок подраздела')),
                ('order', edit_course_zone.utils.fields.OrderField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='edit_course_zone.chapter', verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit_course_zone.testquestion')),
            ],
            options={
                'verbose_name': 'Вложение к вопросу',
                'verbose_name_plural': 'Вложения к вопросам',
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', edit_course_zone.utils.fields.OrderField(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'table', 'code', 'video', 'image', 'file', 'test', 'writeaprogram')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='edit_course_zone.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Содержание урока',
                'verbose_name_plural': 'Содержания уроков',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subchapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edit_course_zone.subchapter', verbose_name='Подраздел'),
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='edit_course_zone.course', verbose_name='Курс')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participates', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участника курса',
                'verbose_name_plural': 'Участники курсов',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='edit_course_zone.course', verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit_course_zone.testanswer')),
            ],
            options={
                'verbose_name': 'Вложение к ответу',
                'verbose_name_plural': 'Вложения к ответам',
            },
        ),
    ]
